title: "Taha's Portfolio"
description: "This is Taha Ouahmane's web portfolio!"
remote_theme: b2a3e8/jekyll-theme-console

header_pages:
  - index.md
  - whoami.md
  - projects.md
  - contact.md

footer: 'Find me on <a href="https://www.linkedin.com/in/taha-ouahmane">LinkedIn</a> <a href="https://github.com/1McLongLong">GitHub</a> <a href="https://tryhackme.com/p/Mclonglong">TryHackMe</a>'

# Build settings
markdown: kramdown
style: nord
listen_for_clients_preferred_style: false
